---
version: "3"
services:
  voci-api:
    image: voci-api:latest
    restart: always
    ports:
      - "28080:8080"
  voci-client:
    image: voci-client:latest
    restart: always
    ports:
      - "28081:3000"
    environment:
      - VOCI_API_URL=http://voci-api:8080
networks:
  default:
    name: voci
